# Generated by Django 3.2.8 on 2021-10-22 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweeter_id', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('tweet_id', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=5000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentiment_score', models.FloatField()),
            ],
            options={
                'verbose_name': ('Tweet',),
                'verbose_name_plural': 'Tweets',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': ('Twitter User',),
                'verbose_name_plural': 'Twitter Users',
            },
        ),
    ]
