# Generated by Django 3.2.8 on 2021-10-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_id', models.CharField(default='', max_length=100)),
                ('ticker_name', models.CharField(max_length=100, null=True)),
                ('exp_return', models.FloatField(null=True)),
                ('exp_risk', models.FloatField(null=True)),
            ],
        ),
    ]
